### ISSUE TITLE
Schema is hard coded

### ISSUE THREAD

**Issue by amsharma9** [Videles/PhalconTime#1]
First of all, thanks for creating this application. I had been wanting to see a sample application like this. I was also struggling with integrating AdminLTE with Phalcon and using datatables. **What you have created is very helpful.**

I think you should avoid hard coding the schema in each model. I had to comment those lines in each model code to get your app to work with my database `testdb`
`$this->setSchema("phalcon-time");`

**Comment by Videles** [comment]
Ah thnx alot for your information! I will remove it if possible or use the database name from app/config/config.php from it. A lot of the model code is automatically generatedby the developer tools and I was not sure wether or not it served any purpose.

**Comment by amsharma9** [comment]
I also use Devtools a lot. I don't use the `schema` option. I have modified Devtools to generate code which uses `forms`. I can share that code if you want. I am still learning. Its been a slow process. I will try to use your code into my application.

**Comment by Videles** [comment]
The set schema function is removed in the last update. Thanks for the notification!
