### ISSUE TITLE
ACL - ControllerBase

### ISSUE THREAD

**Issue by Jurigag** [Videles/PhalconTime#2]
https://github.com/Videles/PhalconTime/blob/4d764692bbe9695a33fef912cd600af068cd1ec1/app/controllers/ControllerBase.php#L119

If you are requiring phalcon 3 you can actually store user objects/models in cache/session and just implements RoleAware interface on this class and use here this object

**Comment by Videles** [comment]
I will have to read/learn more about this. I used the invo and vokuro application as examples. But didnt completly understand how the auth/acl where connected. When I understand how it works I will try to improve it

**Comment by Jurigag** [comment]
https://docs.phalconphp.com/de/3.2/acl#objects

**Comment by Videles** [comment]
Thank you. I'm going to try and make it as shown in the above link next.

**Comment by Videles** [comment]
Would this solution be good also: https://github.com/phalcon/invo/blob/master/app/plugins/SecurityPlugin.php ?

**Comment by Jurigag** [comment]
No, it's old code too, working just on strings.

**Comment by Videles** [comment]
This will be upgraded in a later stadium
