### ISSUE TITLE
ACL - ControllerBase condition

### ISSUE THREAD

**Issue by Jurigag** [Videles/PhalconTime#3]
https://github.com/Videles/PhalconTime/blob/4d764692bbe9695a33fef912cd600af068cd1ec1/app/controllers/ControllerBase.php#L124

Shouldn't here be just If, not elseif?

**Comment by Videles** [comment]
That what I initialy did but then I received the following error:

 Fatal error: Uncaught Error: Call to a member function isAllowed() on null in C:\wamp64\www\phalcon-time\app\controllers\ControllerBase.php on line 125

**Comment by Jurigag** [comment]
Beacause acl is not created. You should set acl as a service really, outside of controller.
