### ISSUE TITLE
Keeping the left sidebar menu open

### ISSUE THREAD

**Issue by amsharma9** [Videles/PhalconTime#4]
I used your commented code on the left sidebar menu and used it to check the issue I am facing with AdminLTE in my code. It has the same issue. I have attached a modified layout.volt. Use it and click on `Verkoop->Projects2`. It will open Projects but close the left menu, i.e. `Verkoop` sub-menu. I would like the left side menu to stay as it is even if any menu or sub-menu is clicked. Only the content should change. Any ideas on how to resolve this. I have a long multi-level left sidebar menu and I am facing the same issue. I copied all your CSS and JS files exactly and tried to see if it will work but it didn't. Let me know if you have a solution.
[layout.zip](https://github.com/Videles/PhalconTime/files/1339109/layout.zip)

Thanks
Amal

**Comment by Videles** [comment]
This is not really related to this repository. But the submenu is open when the mainmenu has the class 'menu-open'. You could use an if statement and check for a self generated variable / controller in .volt. To add the class. Hope this helps you.
